# Generated by Django 2.2.6 on 2020-05-17 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=30)),
                ('descricao_evento', models.CharField(max_length=1000)),
                ('valor_evento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_evento', models.DateTimeField(verbose_name='Data do evento')),
            ],
        ),
    ]
