# Generated by Django 2.2.6 on 2020-05-14 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_entrada', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_entrada', models.DateTimeField(verbose_name='Data do Recebimento')),
            ],
        ),
        migrations.CreateModel(
            name='Saida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_saida', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_saida', models.DateTimeField(verbose_name='Data do Pagamento')),
            ],
        ),
    ]
